using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SimpleForumApp.Domain.Entities.App;

namespace SimpleForumApp.Persistence.EntityFrameworkCore.Configurations.App
{
    public class CountryConfigurations : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder
                .HasOne(x => x.Status)
                .WithMany(y => y.Countries)
                .HasForeignKey(x => x.StatusId)
                .OnDelete(DeleteBehavior.Restrict);

            builder
                .HasData(new List<Country>
                {
                    new() { Id = 1, Name = "Abhazya", StatusId = 1 },
                    new() { Id = 2, Name = "Afganistan", StatusId = 1 },
                    new() { Id = 3, Name = "Almanya", StatusId = 1 },
                    new() { Id = 4, Name = "Amerika Birleşik Devletleri", StatusId = 1 },
                    new() { Id = 5, Name = "Andorra", StatusId = 1 },
                    new() { Id = 6, Name = "Angola", StatusId = 1 },
                    new() { Id = 7, Name = "Antigua ve Barbuda", StatusId = 1 },
                    new() { Id = 8, Name = "Arjantin", StatusId = 1 },
                    new() { Id = 9, Name = "Arnavutluk", StatusId = 1 },
                    new() { Id = 10, Name = "Avusturalya", StatusId = 1 },
                    new() { Id = 11, Name = "Avusturya", StatusId = 1 },
                    new() { Id = 12, Name = "Azerbaycan", StatusId = 1 },
                    new() { Id = 13, Name = "Bahamalar", StatusId = 1 },
                    new() { Id = 14, Name = "Bahreyn", StatusId = 1 },
                    new() { Id = 15, Name = "Bangladeş", StatusId = 1 },
                    new() { Id = 16, Name = "Barbados", StatusId = 1 },
                    new() { Id = 17, Name = "Belçika", StatusId = 1 },
                    new() { Id = 18, Name = "Belize", StatusId = 1 },
                    new() { Id = 19, Name = "Benin", StatusId = 1 },
                    new() { Id = 20, Name = "Belarus", StatusId = 1 },
                    new() { Id = 21, Name = "Bhutan", StatusId = 1 },
                    new() { Id = 22, Name = "Birleşik Arap Emirlikleri", StatusId = 1 },
                    new() { Id = 23, Name = "Birleşik Krallık", StatusId = 1 },
                    new() { Id = 24, Name = "Bolivya", StatusId = 1 },
                    new() { Id = 25, Name = "Bosna-Hersek", StatusId = 1 },
                    new() { Id = 26, Name = "Botsvana", StatusId = 1 },
                    new() { Id = 27, Name = "Brezilya", StatusId = 1 },
                    new() { Id = 28, Name = "Brunei", StatusId = 1 },
                    new() { Id = 29, Name = "Bulgaristan", StatusId = 1 },
                    new() { Id = 30, Name = "Burkina Faso", StatusId = 1 },
                    new() { Id = 31, Name = "Burundi", StatusId = 1 },
                    new() { Id = 32, Name = "Cezayir", StatusId = 1 },
                    new() { Id = 33, Name = "Cibuti", StatusId = 1 },
                    new() { Id = 34, Name = "Çad", StatusId = 1 },
                    new() { Id = 35, Name = "Çekya", StatusId = 1 },
                    new() { Id = 36, Name = "Çin", StatusId = 1 },
                    new() { Id = 37, Name = "Danimarka", StatusId = 1 },
                    new() { Id = 38, Name = "Doğu Timor", StatusId = 1 },
                    new() { Id = 39, Name = "Dominik Cumhuriyeti", StatusId = 1 },
                    new() { Id = 40, Name = "Dominika", StatusId = 1 },
                    new() { Id = 41, Name = "Ekvador", StatusId = 1 },
                    new() { Id = 42, Name = "Ekvator Ginesi", StatusId = 1 },
                    new() { Id = 43, Name = "El Salvador", StatusId = 1 },
                    new() { Id = 44, Name = "Endonezya", StatusId = 1 },
                    new() { Id = 45, Name = "Eritre", StatusId = 1 },
                    new() { Id = 46, Name = "Ermenistan", StatusId = 1 },
                    new() { Id = 47, Name = "Estonya", StatusId = 1 },
                    new() { Id = 48, Name = "Esvatini", StatusId = 1 },
                    new() { Id = 49, Name = "Etiyopya", StatusId = 1 },
                    new() { Id = 50, Name = "Fas", StatusId = 1 },
                    new() { Id = 51, Name = "Fiji", StatusId = 1 },
                    new() { Id = 52, Name = "Fildişi Sahili", StatusId = 1 },
                    new() { Id = 53, Name = "Filipinler", StatusId = 1 },
                    new() { Id = 54, Name = "Filistin", StatusId = 1 },
                    new() { Id = 55, Name = "Finlandiya", StatusId = 1 },
                    new() { Id = 56, Name = "Fransa", StatusId = 1 },
                    new() { Id = 57, Name = "Gabon", StatusId = 1 },
                    new() { Id = 58, Name = "Gambiya", StatusId = 1 },
                    new() { Id = 59, Name = "Gana", StatusId = 1 },
                    new() { Id = 60, Name = "Gine", StatusId = 1 },
                    new() { Id = 61, Name = "Gine-Bissau", StatusId = 1 },
                    new() { Id = 62, Name = "Girenada", StatusId = 1 },
                    new() { Id = 63, Name = "Guyana", StatusId = 1 },
                    new() { Id = 64, Name = "Guatemala", StatusId = 1 },
                    new() { Id = 65, Name = "Güney Afrika Cumhuriyeti", StatusId = 1 },
                    new() { Id = 66, Name = "Güney Kıbrıs", StatusId = 1 },
                    new() { Id = 67, Name = "Güney Kore", StatusId = 1 },
                    new() { Id = 68, Name = "Güney Osetya", StatusId = 1 },
                    new() { Id = 69, Name = "Güney Sudan", StatusId = 1 },
                    new() { Id = 70, Name = "Gürcistan", StatusId = 1 },
                    new() { Id = 71, Name = "Haiti", StatusId = 1 },
                    new() { Id = 72, Name = "Hırvatistan", StatusId = 1 },
                    new() { Id = 73, Name = "Hindistan", StatusId = 1 },
                    new() { Id = 74, Name = "Hollanda", StatusId = 1 },
                    new() { Id = 75, Name = "Honduras", StatusId = 1 },
                    new() { Id = 76, Name = "Irak", StatusId = 1 },
                    new() { Id = 77, Name = "İran", StatusId = 1 },
                    new() { Id = 78, Name = "İrlanda", StatusId = 1 },
                    new() { Id = 79, Name = "İspanya", StatusId = 1 },
                    new() { Id = 80, Name = "İsrail", StatusId = 1 },
                    new() { Id = 81, Name = "İsveç", StatusId = 1 },
                    new() { Id = 82, Name = "İsviçre", StatusId = 1 },
                    new() { Id = 83, Name = "İtalya", StatusId = 1 },
                    new() { Id = 84, Name = "İzlanda", StatusId = 1 },
                    new() { Id = 85, Name = "Jamaika", StatusId = 1 },
                    new() { Id = 86, Name = "Japonya", StatusId = 1 },
                    new() { Id = 87, Name = "Kamboçya", StatusId = 1 },
                    new() { Id = 88, Name = "Kamerun", StatusId = 1 },
                    new() { Id = 89, Name = "Kanada", StatusId = 1 },
                    new() { Id = 90, Name = "Karadağ", StatusId = 1 },
                    new() { Id = 91, Name = "Katar", StatusId = 1 },
                    new() { Id = 92, Name = "Kazakistan", StatusId = 1 },
                    new() { Id = 93, Name = "Kenya", StatusId = 1 },
                    new() { Id = 94, Name = "Kırgızistan", StatusId = 1 },
                    new() { Id = 95, Name = "Kiribati", StatusId = 1 },
                    new() { Id = 96, Name = "Kolombiya", StatusId = 1 },
                    new() { Id = 97, Name = "Komorlar", StatusId = 1 },
                    new() { Id = 98, Name = "Kongo Cumhuriyeti", StatusId = 1 },
                    new() { Id = 99, Name = "Kongo DC", StatusId = 1 },
                    new() { Id = 100, Name = "Kosova", StatusId = 1 },
                    new() { Id = 101, Name = "Kosta Rika", StatusId = 1 },
                    new() { Id = 102, Name = "Kuveyt", StatusId = 1 },
                    new() { Id = 103, Name = "Kuzey Kıbrık Türk Cumhuriyeti", StatusId = 1 },
                    new() { Id = 104, Name = "Kuzey Kore", StatusId = 1 },
                    new() { Id = 105, Name = "Kuzey Makedonya", StatusId = 1 },
                    new() { Id = 106, Name = "Küba", StatusId = 1 },
                    new() { Id = 107, Name = "Laos", StatusId = 1 },
                    new() { Id = 108, Name = "Lesotho", StatusId = 1 },
                    new() { Id = 109, Name = "Letonya", StatusId = 1 },
                    new() { Id = 110, Name = "Liberya", StatusId = 1 },
                    new() { Id = 111, Name = "Libya", StatusId = 1 },
                    new() { Id = 112, Name = "Lihtenştayn", StatusId = 1 },
                    new() { Id = 113, Name = "Litvanya", StatusId = 1 },
                    new() { Id = 114, Name = "Lübnan", StatusId = 1 },
                    new() { Id = 115, Name = "Lüksemburg", StatusId = 1 },
                    new() { Id = 116, Name = "Maceristan", StatusId = 1 },
                    new() { Id = 117, Name = "Madagaskar", StatusId = 1 },
                    new() { Id = 118, Name = "Matavi", StatusId = 1 },
                    new() { Id = 119, Name = "Maldivler", StatusId = 1 },
                    new() { Id = 120, Name = "Malezya", StatusId = 1 },
                    new() { Id = 121, Name = "Mali", StatusId = 1 },
                    new() { Id = 122, Name = "Malta", StatusId = 1 },
                    new() { Id = 123, Name = "Marshall Adaları", StatusId = 1 },
                    new() { Id = 124, Name = "Mauritius", StatusId = 1 },
                    new() { Id = 125, Name = "Meksika", StatusId = 1 },
                    new() { Id = 126, Name = "Mısır", StatusId = 1 },
                    new() { Id = 127, Name = "Mikronezya Federal Devletleri", StatusId = 1 },
                    new() { Id = 128, Name = "Moğolistan", StatusId = 1 },
                    new() { Id = 129, Name = "Moldova", StatusId = 1 },
                    new() { Id = 130, Name = "Monako", StatusId = 1 },
                    new() { Id = 131, Name = "Moritanya", StatusId = 1 },
                    new() { Id = 132, Name = "Mozambik", StatusId = 1 },
                    new() { Id = 133, Name = "Myanmar", StatusId = 1 },
                    new() { Id = 134, Name = "Namibya", StatusId = 1 },
                    new() { Id = 135, Name = "Nauru", StatusId = 1 },
                    new() { Id = 136, Name = "Nepal", StatusId = 1 },
                    new() { Id = 137, Name = "Nikaragua", StatusId = 1 },
                    new() { Id = 138, Name = "Nijer", StatusId = 1 },
                    new() { Id = 139, Name = "Nijerya", StatusId = 1 },
                    new() { Id = 140, Name = "Norveç", StatusId = 1 },
                    new() { Id = 141, Name = "Orta Afrika Cumhuriyeti", StatusId = 1 },
                    new() { Id = 142, Name = "Özbekistan", StatusId = 1 },
                    new() { Id = 143, Name = "Pakistan", StatusId = 1 },
                    new() { Id = 144, Name = "Palau", StatusId = 1 },
                    new() { Id = 145, Name = "Panama", StatusId = 1 },
                    new() { Id = 146, Name = "Papua Yeni Gine", StatusId = 1 },
                    new() { Id = 147, Name = "Paraguay", StatusId = 1 },
                    new() { Id = 148, Name = "Peru", StatusId = 1 },
                    new() { Id = 149, Name = "Polonya", StatusId = 1 },
                    new() { Id = 150, Name = "Portekiz", StatusId = 1 },
                    new() { Id = 151, Name = "Romanya", StatusId = 1 },
                    new() { Id = 152, Name = "Ruanda", StatusId = 1 },
                    new() { Id = 153, Name = "Rusya", StatusId = 1 },
                    new() { Id = 154, Name = "Sahra Demokratik Arap Cumhuriyeti", StatusId = 1 },
                    new() { Id = 155, Name = "Saint Kitts ve Nevis", StatusId = 1 },
                    new() { Id = 156, Name = "Saint Lucia", StatusId = 1 },
                    new() { Id = 157, Name = "Saint Vincent ve Grenadinler", StatusId = 1 },
                    new() { Id = 158, Name = "Samoa", StatusId = 1 },
                    new() { Id = 159, Name = "San Marino", StatusId = 1 },
                    new() { Id = 160, Name = "São Tomé ve Príncipe", StatusId = 1 },
                    new() { Id = 161, Name = "Senegal", StatusId = 1 },
                    new() { Id = 162, Name = "Seyşeller", StatusId = 1 },
                    new() { Id = 163, Name = "Sırbistan", StatusId = 1 },
                    new() { Id = 164, Name = "Sierra Leone", StatusId = 1 },
                    new() { Id = 165, Name = "Singapur", StatusId = 1 },
                    new() { Id = 166, Name = "Slovakya", StatusId = 1 },
                    new() { Id = 167, Name = "Slovenya", StatusId = 1 },
                    new() { Id = 168, Name = "Solomon Adaları", StatusId = 1 },
                    new() { Id = 169, Name = "Somali", StatusId = 1 },
                    new() { Id = 170, Name = "Somaliland", StatusId = 1 },
                    new() { Id = 171, Name = "Sri Lanka", StatusId = 1 },
                    new() { Id = 172, Name = "Sudan", StatusId = 1 },
                    new() { Id = 173, Name = "Surinam", StatusId = 1 },
                    new() { Id = 174, Name = "Suriye", StatusId = 1 },
                    new() { Id = 175, Name = "Suudi Arabistan", StatusId = 1 },
                    new() { Id = 176, Name = "Şili", StatusId = 1 },
                    new() { Id = 177, Name = "Tacikistan", StatusId = 1 },
                    new() { Id = 178, Name = "Tanzanya", StatusId = 1 },
                    new() { Id = 179, Name = "Tayland", StatusId = 1 },
                    new() { Id = 180, Name = "Tayvan", StatusId = 1 },
                    new() { Id = 181, Name = "Togo", StatusId = 1 },
                    new() { Id = 182, Name = "Tonga", StatusId = 1 },
                    new() { Id = 183, Name = "Transdinyester", StatusId = 1 },
                    new() { Id = 184, Name = "Trinidad ve Tobago", StatusId = 1 },
                    new() { Id = 185, Name = "Tunus", StatusId = 1 },
                    new() { Id = 186, Name = "Türkiye", StatusId = 1 },
                    new() { Id = 187, Name = "Türkmenistan", StatusId = 1 },
                    new() { Id = 188, Name = "Türkmenistan", StatusId = 1 },
                    new() { Id = 189, Name = "Uganda", StatusId = 1 },
                    new() { Id = 190, Name = "Ukrayna", StatusId = 1 },
                    new() { Id = 191, Name = "Umman", StatusId = 1 },
                    new() { Id = 192, Name = "Uruguay", StatusId = 1 },
                    new() { Id = 193, Name = "Ürdün", StatusId = 1 },
                    new() { Id = 194, Name = "Vanuatu", StatusId = 1 },
                    new() { Id = 195, Name = "Vatikan", StatusId = 1 },
                    new() { Id = 196, Name = "Venezüela", StatusId = 1 },
                    new() { Id = 197, Name = "Vietnam", StatusId = 1 },
                    new() { Id = 198, Name = "Yemen", StatusId = 1 },
                    new() { Id = 199, Name = "Yeni Zelanda", StatusId = 1 },
                    new() { Id = 200, Name = "Yeşil Burun Adaları", StatusId = 1 },
                    new() { Id = 201, Name = "Yunanistan", StatusId = 1 },
                    new() { Id = 202, Name = "Zambiya", StatusId = 1 },
                    new() { Id = 203, Name = "Zimbabve", StatusId = 1 }
                });
        }
    }
}
